export const FETCH_ACTIVITY = "FETCH_ACTIVITY";
export const NEW_ACTIVITY = "NEW_ACTIVITY";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_REFRESH = "FETCH_REFRESH";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const FETCH_STORE_ITEMS = "FETCH_STORE_ITEMS";

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

//order

export const CREATE_ORDER = "CREATE_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_TABLE = "FETCH_TABLE";
export const LEAVE_TABLE = "LEAVE_TABLE";
// export const SELECT_ORDER = "SELECT_ORDER";

// translation
export const FETCH_TRANSLATION = "FETCH_TRANSLATION";
export const FETCH_ALL_TRANSLATION = "FETCH_ALL_TRANSLATION";

//customer

export const ANONYMOUS_LOGIN_CUSTOMER = "ANONYMOUS_LOGIN_CUSTOMER";
export const LOGIN_CUSTOMER = "LOGIN_CUSTOMER";
export const LOGOUT_CUSTOMER = "LOGOUT_CUSTOMER";
export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const RESTART_AUTH_RESPONSE = "RESTART_AUTH_RESPONSE";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_ALLERGENS = "UPDATE_CUSTOMER_ALLERGENS";

//Checkout

export const PAYMENT_ORDERS = "PAYMENT_ORDERS";
export const SELECT_ORDER = "SELECT_ORDER";
export const PAYMENT_DONE = "PAYMENT_DONE";
export const ADD_TIPS = "ADD_TIPS";
export const ADD_CARD = "ADD_CARD";

//Allergen

export const FETCH_ALLERGEN = "FETCH_ALLERGEN";
export const REFRESH_ALLERGEN = "REFRESH_ALLERGEN";
